### ISSUE TITLE
Custom HTML landmarks

### ISSUE THREAD

**Issue by seaj1one** [builderius/builderius#21]
There's an extensive list already in Builderius, but it's missing a few. Can I add an HTML landmark instead? You can have a field called custom HTML rather than you adding them manually on your end.

**Comment by mrpsiho** [comment]
Could you clarify, please?

**Comment by seaj1one** [comment]
Yeah sure - Sorry I meant HTML tags.

It maybe easier if I could add custom tags as new ones are created. 

https://www.w3schools.com/tags/default.asp

**Comment by mrpsiho** [comment]
Potentially, it is an interesting idea. However, let's clarify this - it is not enough just write a custom tag name. Such tag must be defined via JS. Then, custom html tags are non useful on its own. They become useful when you scope some specific functionalities via JS inside. Is it really what you need?

**Comment by seaj1one** [comment]
It's only really for accessibility. Screen readers will announce things like buttons, forms and tables. People who are partially or blind wouldn't be able to use the internet overwise.

https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML

**Comment by mrpsiho** [comment]
It is a different topic now. Accessibility is not connected directly to custom HTML tags.
This article is about custom HTML tags: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements Is this what you meant in the first place?

**Comment by seaj1one** [comment]
No, I meant for accessibility reasons. I should have included this initially to make it easier for you. 

This is what I meant "https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML"

Below is an article and a screenshot from their page. Brick includes a few HTML tags but allows you to add an HTML tag that's not listed. 

https://academy.bricksbuilder.io/article/accessibility/

![image](https://user-images.githubusercontent.com/72103864/191827969-91cef05e-a896-4f00-8b1f-eb071fcbf9b2.png)

**Comment by mrpsiho** [comment]
I do not know why this or that builder does this or that. I just can say for Builderius, because I am one of its developers. :)

**The short answer.** Please, just let me know what tag do you need and I will add it in no time. It is really better option here.

**The long answer.** We have tried to add as many as possible standard tags and also bring some order in development "out of the box". And also help developers to follow best practices, not just write anything everywhere. To make the builder a kind of an instrument of learning. This is why we have settings validation in many places at least and also this is why we have the set of modules as we have it. The most of the modules have also validation on output. Please, check the MDN, there is always "permitted content" info. Not all tags might be placed in other tags. And it should be respected. Like anchor inside another anchor, or from within form or many tags are not allowed inside table row etc. I don't really think there should be option "custom" and possibility to write anything you want.

**Comment by seaj1one** [comment]
Many thanks for explaining, I understand. 

Should I email support as the preferred method or on GitHub?

**Comment by mrpsiho** [comment]
Please, create a ticket here. We take into account the tickets created and trying to resolve them asap. Thanks!
